name: test action
on:
  workflow_dispatch:
jobs:
  ci:
    uses: complete-github-setup/.github/.github/workflows/ci.yaml@main

  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
